---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tf-helloworld
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/protomonk/tf-helloworld
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: flux-system
spec:
  approvePlan: auto
  path: ./
  interval: 1m
  storeReadablePlan: human
  sourceRef:
    kind: GitRepository
    name: tf-helloworld
    namespace: flux-system
  writeOutputsToSecret:
    name: tf-helloworld-output
